# Generated by Django 5.1.4 on 2025-01-09 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_sizeoption_slug_alter_orderitem_product_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.productitem'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
