# Generated by Django 5.1.4 on 2025-01-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_payment_stripe_charge_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
